package tun.app.holidays.model;

/**
 * Created by nourjbel on 28/02/2015.
 */
public enum HolidayType {
    HOLIDAY_PAYED,
    HOLIDAY_NOT_PAYED,
    HOLIDAY_RTT,
    HOLIDAY_RTT_EMPLOYEE,
    HOLIDAY_RTT_EMPLOYER,
    HOLIDAY_PATERNITY,
    HOLIDAY_MATERNITY,
    HOLIDAY_DEATH,
    HOLIDAY_HEALTH,
    HOLIDAY_MARRIAGE,
    HOLIDAY_TRAINING,
    HOLIDAY_VIP,
    HOLIDAY_CUSTOM


}
